/**
 * Build the icon sprite from lucide-static.
 *
 * The paths are read out of the installed package rather than transcribed,
 * because hand-copied path data is unreviewable — a wrong coordinate looks
 * exactly like a right one in a diff. Run this again to change the mapping or
 * pick up a newer Lucide; the output is committed so nothing is fetched at
 * build or run time and the CSP can keep `default-src 'self'`.
 *
 *   node scripts/build-icons.mjs
 */

import { readFile, writeFile } from 'node:fs/promises';

const SRC = 'node_modules/lucide-static/icons';
const TARGET = 'public/index.html';

/**
 * Sprite id → Lucide icon name.
 *
 * `solid: true` fills the glyph as well as stroking it. Lucide is an outline
 * set, and outline is right for affordances in a settings list — but the
 * transport is the one place where weight carries meaning. A hairline triangle
 * inside a 64px brass button reads as disabled. Every one of these is a closed
 * path or a rect, so filling it is well defined; the bar in skip-forward is an
 * open path and fills to nothing, which is what we want.
 *
 * `heart` is neither: outline when not a favourite, filled when it is. It
 * cannot use a plain attribute for that, so it takes a custom property — those
 * inherit into a <use> shadow tree, where a CSS selector cannot reach.
 */
const MAP = {
  'i-play': { icon: 'play', solid: true },
  'i-pause': { icon: 'pause', solid: true },
  'i-prev': { icon: 'skip-back', solid: true },
  'i-next': { icon: 'skip-forward', solid: true },
  'i-heart': { icon: 'heart', fill: 'var(--icon-fill, none)' },
  'i-close': { icon: 'x' },
  'i-plus': { icon: 'plus' },
  'i-search': { icon: 'search' },
  'i-list': { icon: 'list-music' },
  'i-gear': { icon: 'sliders-horizontal' },
  'i-copy': { icon: 'copy' },
  'i-trash': { icon: 'trash-2' },
  'i-download': { icon: 'download' },
  // Cloud-with-tick and circle-with-tick, matching what they meant before:
  // "in the cloud library" and "on this device".
  'i-cloud': { icon: 'cloud-check' },
  'i-cached': { icon: 'circle-check' },
  // Repeat-all, repeat-one, shuffle.
  'i-seq': { icon: 'repeat' },
  'i-single': { icon: 'repeat-1' },
  'i-shuffle': { icon: 'shuffle' },
  'i-chevron': { icon: 'chevron-down' },
};

/** Inner markup of a Lucide file, normalised to one line. */
async function glyph(name) {
  const raw = await readFile(`${SRC}/${name}.svg`, 'utf8');
  const open = raw.indexOf('>', raw.indexOf('<svg'));
  const body = raw.slice(open + 1, raw.lastIndexOf('</svg>'));
  return body.replace(/\s+/g, ' ').replace(/\s*\/>/g, '/>').trim();
}

const symbols = [];
for (const [id, { icon, solid, fill }] of Object.entries(MAP)) {
  const paint = fill ?? (solid ? 'currentColor' : 'none');
  symbols.push(
    `    <symbol id="${id}" viewBox="0 0 24 24" fill="${paint}" stroke="currentColor" ` +
      `stroke-width="var(--icon-stroke, 2)" stroke-linecap="round" ` +
      `stroke-linejoin="round">` +
      `${await glyph(icon)}</symbol>`
  );
}

const banner = `<!-- Icon sprite: Lucide (ISC), generated by scripts/build-icons.mjs — do not
     hand-edit the symbols; change the mapping in that script and re-run it.
     Vendored rather than loaded from a CDN so the CSP can keep
     \`default-src 'self'\`.

     Every glyph is a <symbol> on Lucide's native 24x24 grid. A symbol carries
     its own viewBox, so it scales to whatever box the referencing <svg> is
     given and the outer viewBox no longer has to agree with the sprite — which
     is what the previous 256x256 sprite required, and what the brand mark got
     wrong. \`stroke="currentColor"\` is what lets a single <use> be recoloured
     from CSS, and \`--icon-stroke\` its weight — a custom property rather than a
     plain attribute because those are the only thing that inherits into a
     <use> shadow tree, where a CSS selector cannot reach. -->`;

let html = await readFile(TARGET, 'utf8');

// Replace the banner.
const oldBanner = html.match(/<!-- Icon sprite:[\s\S]*?-->/);
if (!oldBanner) throw new Error('sprite banner not found');
html = html.replace(oldBanner[0], banner);

// Replace every mapped glyph. i-vane is deliberately untouched: it stays a <g>
// because the dial wraps it in a hand-tuned translate/scale, and a <symbol>
// would establish its own viewport and ignore that.
// Matches either form, so this script is re-runnable: the first pass turns a
// <g> into a <symbol>, and without this the second pass would find nothing and
// throw. A generator that only works once is a generator nobody re-runs.
const ids = Object.keys(MAP);
for (const [i, id] of ids.entries()) {
  const re = new RegExp(`^[ \\t]*<(g|symbol) id="${id}"[^>]*>.*?</\\1>[ \\t]*$`, 'm');
  if (re.test(html)) {
    html = html.replace(re, symbols[i]);
  } else {
    // A newly mapped id has nothing to replace, so it is appended. Adding an
    // icon should mean editing MAP and nothing else.
    html = html.replace(/^([ \t]*)<(g|symbol) id="i-vane"/m, `${symbols[i]}\n$1<$2 id="i-vane"`);
    console.log(`  + ${id} (new)`);
  }
}

// The referencing viewBox is now redundant for symbols, and was actively wrong
// for the 24-unit vane path in the brand mark.
html = html.replaceAll('viewBox="0 0 256 256"', 'viewBox="0 0 24 24"');

await writeFile(TARGET, html);

/* Every reference must resolve. A `<use href="#i-typo">` renders nothing at
   all — no error, no console warning, just an empty button — so this is checked
   rather than trusted. JS builds icon markup too, so those are scanned as
   well. */
const defined = new Set([...html.matchAll(/<(?:g|symbol) id="(i-[\w-]+)"/g)].map((m) => m[1]));
const sources = ['public/index.html', 'public/src/main.js', 'public/src/list.js'];
const missing = [];
for (const file of sources) {
  const text = await readFile(file, 'utf8');
  for (const m of text.matchAll(/#(i-[\w-]+)/g)) {
    if (!defined.has(m[1])) missing.push(`${file}: #${m[1]}`);
  }
}
// list.js maps names through an ICONS table, so check its values too.
const listjs = await readFile('public/src/list.js', 'utf8');
for (const m of listjs.matchAll(/'(i-[\w-]+)'/g)) {
  if (!defined.has(m[1])) missing.push(`public/src/list.js: ${m[1]}`);
}
if (missing.length) {
  console.error(`\nunresolved icon references:\n${missing.map((x) => `  ✗ ${x}`).join('\n')}\n`);
  process.exit(1);
}

console.log(
  `${TARGET} — ${symbols.length} Lucide symbols, ${defined.size} ids, all references resolve`
);
